apiVersion: apps/v1
kind: Deployment

metadata: 
  name: serve-deployment

spec:
  replicas: 1
  
  selector: 
    matchLabels: 
      component: api
  
  template:
    metadata:
      labels: 
        component: api
    
    spec:
      containers:
        - name: ServeNode
          image: saphalpantha/serve-node
          ports: 
            - containerPort: 5000